server:
  port: 8206
spring:
  application:
    name: service-product
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.184.11:3306/gmall_product
    username: root
    password: root
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.184.11:8848
  zipkin:
    base-url: http://192.168.184.11:9411
  redis:
    host: 192.168.184.11
    password:
    database: 0
    port: 6379
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml