server:
  port: 80
spring:
  application:
    name: gmall-gateway
#    配置了注册中心地址，还启用了服务发现功能，可以实现微服务的动态发现和调用
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.184.11:8848
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: service-product
          uri: lb://service-product
          predicates:
            - Path=/*/product/**


